// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbwLufzF-HmMZhy6IAyE652EuF_b8mGs',
    appId: '1:956584707773:web:0d9dcc5028741f8b4819d4',
    messagingSenderId: '956584707773',
    projectId: 'internship-823b6',
    authDomain: 'internship-823b6.firebaseapp.com',
    storageBucket: 'internship-823b6.appspot.com',
    measurementId: 'G-XBYSJ0ESLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJrtUzKiG_lClehw-iX6mKrv_wXx08dE',
    appId: '1:956584707773:android:11e3e4f591969da24819d4',
    messagingSenderId: '956584707773',
    projectId: 'internship-823b6',
    storageBucket: 'internship-823b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_NzMz90x3IxJhmdfPa99EBpTefi8FCI',
    appId: '1:956584707773:ios:194b75f4094fbf214819d4',
    messagingSenderId: '956584707773',
    projectId: 'internship-823b6',
    storageBucket: 'internship-823b6.appspot.com',
    iosClientId: '956584707773-omiosmttfvj4jmgdm4i513k3ohv406ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.alemenoAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3_NzMz90x3IxJhmdfPa99EBpTefi8FCI',
    appId: '1:956584707773:ios:194b75f4094fbf214819d4',
    messagingSenderId: '956584707773',
    projectId: 'internship-823b6',
    storageBucket: 'internship-823b6.appspot.com',
    iosClientId: '956584707773-omiosmttfvj4jmgdm4i513k3ohv406ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.alemenoAssigment',
  );
}
